
### Register user
POST http://localhost:3030/users/register
Content-Type: application/json

{
    "username":"sammy",
    "email":"samuelmwaniki17@gmail.com",
    "password":"sammy"
}

# {
#     "username":"kim",
#     "email":"kimachia1@gmail.com",
#     "password":"pass"

# }




### Login
POST http://localhost:3030/users/login
Content-Type: application/json
token:

{
    "email":"samuelmwaniki17@gmail.com",
    "password":"sam"
}


### Reset password
POST http://localhost:3030/users/reset
Content-Type: application/json

{
    "email":"kimachia@gmail.com"
}

### Confirm code
POST http://localhost:3030/users/verifycode
Content-Type: application/json

{
    "email":"kimachia@gmail.com",
    "code":"fe00"
}

### change password
POST http://localhost:3030/users/changepwd
Content-Type: application/json

{
    "email":"kimachia@gmail.com",
    "password":"password2"
}


### verify user
POST http://localhost:3030/users/verifyuser
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbW15IiwiZW1haWwiOiJzYW11ZWxtd2FuaWtpMTdAZ21haWwuY29tIiwiaWQiOiJmYzdlMTIxNy00Y2Y5LTRlMGEtYmY1OS01YTM5NDEwMWRlNzYiLCJpYXQiOjE2OTI0Mjc2NjAsImV4cCI6MTY5MjQ0MjA2MH0.F3ibNyFQWyFY5KKyr1_B0-yJSCwAnjcFTjprIqpf3jI
